---
-   name: ssh keys setup
    gather_facts: false
    hosts:
    - ubuntu
    tasks:
    -   name: Create ${HOME}/.ssh if it doesn't exist
        ansible.builtin.file:
            path: ${HOME}/.ssh
            state: directory
            mode: '0700'
    -   name: Copy id_ed25519.pub to ${HOME}/.ssh
        ansible.builtin.copy:
            src: "{{local_home}}/.ssh/id_ed25519.pub"
            dest: ${HOME}/.ssh/id_ed25519.pub
            owner: ubuntu
            group: ubuntu
            mode: '0644'
