---
-   name: set hostname
    gather_facts: false
    hosts:
    - ubuntu
    tasks:
    -   name: copy authorized_keys to /home/ubuntu/.ssh/authorized_keys
        ansible.builtin.copy:
            src: /Users/arobel/repos/ansible-aiml/authorized_keys/authorized_keys
            dest: "{{user_home}}/.ssh/authorized_keys"
            mode: '0600'
