---
-   name: set hostname
    gather_facts: false
    hosts:
    - ubuntu
    tasks:
    -   name: copy hfile to /home/ubuntu/hfile
        ansible.builtin.copy:
            src: /Users/arobel/repos/ansible-aiml/hfile/hfile
            dest: "{{user_home}}/hfile"
            mode: '0644'
