---
-   name: set hostname
    gather_facts: false
    hosts:
    - ubuntu
    tasks:
    -   name: copy hfile to /home/ubuntu/hfile
        ansible.builtin.copy:
            src: "{{local_home}}/repos/ansible-aiml/hfile/hfile"
            dest: "{{user_home}}/hfile"
            mode: '0644'
