---
-   name: install torch_ucc
    gather_facts: false
    hosts:
    - ubuntu
    tasks:
    -   name: get http://172.26.251.99/tftp/packages/ucc_src_lib_pkgs.tgz
        ansible.builtin.get_url:
            url: http://172.26.251.99/tftp/packages/ucc_src_lib_pkgs.tgz
            dest: "{{user_home}}"
            mode: '0766'
    -   name: uncompress ucc_src_lib_pkgs.tgz
        ansible.builtin.unarchive:
            dest: "{{user_home}}"
            src: "{{user_home}}/ucc_src_lib_pkgs.tgz"
            owner: ubuntu
            group: ubuntu
            remote_src: true
    -   name: install torch_ucc
        become: true
        become_user: root
        environment:
            UCX_HOME: "{{user_home}}/ucx/install"
            UCC_HOME: "{{user_home}}/ucc/install"
            WITH_CUDA: no
            CUDA_HOME: ""
            VIRTUAL_ENV: /home/ubuntu/py311
            VIRTUAL_ENV_DISABLE_PROMPT: true
            PYTHONPATH: /usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/home/ubuntu/py311/lib/python3.8/site-packages
        ansible.builtin.shell:
            chdir: "{{user_home}}/torch_ucc"
            cmd: python3 setup.py install
