---
-   name: git clone https://github.com/facebookresearch/param
    gather_facts: false
    hosts:
    - ubuntu
    become: true
    become_user: root
    tasks:
    -   name: git clone https://github.com/facebookresearch/param
        ansible.builtin.git:
            repo: https://github.com/facebookresearch/param
            dest: "{{user_home}}/param"
            force: yes


